on:
  push:
    branches: main

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "22.17.2"
      - run: npm ci
      - run: npm test --if-present
      - run: npx tsc
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          provenance: true
          access: public
          ignore-scripts: true
